language: python
python:
  - 3.6
  - nightly
install:
  - pip3 install -r requirements.txt
  - pip3 install coveralls
  - pip3 install codecov
cache: pip3
script:
  - pytest test.py
  - coverage run test.py

aftersuccess:
  - codecov
       

